### ISSUE TITLE
Limit number of CPUs

### ISSUE THREAD

**Issue by soichih** [BIDS-Apps/rsHRF#1]
Hello.

Is there a way to limit the number of CPU/processes used to run this app?

It seems to always run up-to 8 cores according to my monitoring.

![image](https://user-images.githubusercontent.com/923896/59057160-c6cf6380-8867-11e9-9777-894e29b3ab60.png)

Does it always require 8 cores?

**Comment by madhur-tandon** [comment]
Hi @soichih Thanks for pointing out. Currently, the application runs on all the physical cores that are available. So if you have a 6-core machine, the application would speed up the computation to run parallel stuff on all the 6 cores. 

But I get your point, I would soon send a PR which will enable you to control the number of cores that you want to give to this application. Something like `--n_jobs=3` in addition to the existing command line arguments.

**Comment by soichih** [comment]
Yes, that will be perfect. Thanks! We need to be able to control the number of processes as we are running this App on our HPC system. Each compute-node has up to 24 cores, but scheduler will certainly kill the job if it exceeds the required number of CPUs (I am requesting 8 cores at the moment).

**Comment by madhur-tandon** [comment]
@soichih This has been tackled with the new release of version 1.0.1. The commit has been pushed to the repository. The continuous integration system will now update the packages at both PyPI and DockerHub.

However, it takes around 30 mins to push the latest docker image on DockerHub. Nevertheless, the package on PyPI would have been updated at the time of writing this comment.

If you are using the command line (installed through `pip3 install rsHRF`), you might be able to upgrade to version 1.0.1 right now.

If you are using the containerized BIDS-App through docker, I suggest you wait for around 30 minutes.

Lastly, the input argument to control the number of parallel jobs is given by `--n_jobs 3` (if you want to use 3 parallel processing elements)

Thus, in your existing workflow, the command becomes:

`rsHRF ../bids-data ../results participant --brainmask --estimation canon2dd --participant_label 01 02 --n_jobs 3` (emphasis on `--n_jobs 3`)

If you do not provide this argument, the application will default to using all the physical cores available in your system.

Hope this helps!

**Comment by madhur-tandon** [comment]
Update: Docker Image has been updated.
