### ISSUE TITLE
small fix in the knee point estimation and deconvolution

### ISSUE THREAD

**Issue by danielemarinazzo** [BIDS-Apps/rsHRF#10]
Hi,

we have made a small modification to the matlab code in two scripts

https://github.com/compneuro-da/rsHRF/blob/master/rsHRF_knee_pt.m
https://github.com/compneuro-da/rsHRF/blob/master/rsHRF_iterative_wiener_deconv.m

Basically this is to make sure that the knee point is always found in the decreasing phase of the error, and not in the increasing one. The latter would happen not so often, but it could happen in extreme cases.

The fix should be pretty straightforward.

thanks!

**Comment by danielemarinazzo** [comment]
The fix should be the following

_This is the current estimation_
```
    y=np.ravel(erm)
	x, idx = knee.knee_pt(y)
```
To which we should add	
```
	idm=np.argmin(y)
	ratio=abs(y(idx)-y(idm))/np.ptp(y)
	if ratio>0.5
		idx = idm;
    if idx == nlag-1:
        idx = idx - 1
```

Can you please check if it makes sense, and if yes, implement it after every "knee" estimation in the code?

thanks!

**Comment by AmoghJohri** [comment]
Fix for knee_pt: https://github.com/BIDS-Apps/rsHRF/commit/2ee6ec9a2a29caaaaefe8b64b3b78888a4704da5
Fix for wiener_deconv: https://github.com/BIDS-Apps/rsHRF/commit/11223efb340cc3017317de2aad4810af618b3e04
